<<<<<<< HEAD
# Generated by Django 4.0.7 on 2023-07-05 11:16

from django.db import migrations, models
=======
# Generated by Django 4.0.7 on 2023-07-08 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> post


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('users', '0002_alter_baseuser_email'),
>>>>>>> post
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('text', models.TextField(blank=True)),
            ],
=======
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
>>>>>>> post
        ),
    ]
