# Generated by Django 4.0.7 on 2023-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_text_post_content_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
